### ISSUE TITLE
What is chunk size for repoducing results on CrossCodeEval?

### ISSUE THREAD

**Issue by keezen** [amazon-science/Repoformer#9]
Hello, I am trying to reproduce results on CrossCodeEval reported in your paper.

In your Repoformer paper, the retrieval chunk size is declared as 20. 
But in the actual CrossCodeEval data downloaded from https://github.com/amazon-science/cceval, the chunk size is 10.

![image](https://github.com/user-attachments/assets/eef8afb8-8b7f-4b57-aa09-83647dbf031e)

Could you provide the real chunk size in your report of CrossCodeEval?
![屏幕截图 2024-09-09 113518](https://github.com/user-attachments/assets/28806afa-0d6a-479f-b7be-e29d5082b2c2)

**Comment by xiaowu0162** [comment]
Hi @keezen ,

Thank you for raising the clarification question. We used the official CrossCodeEval data for evaluation, which uses chunk size 10 for retrieval. For RepoEval and CrossCodeLongEval, the chunk size is as specified in the paper.

**Comment by keezen** [comment]
> Hi @keezen ,
> 
> Thank you for raising the clarification question. We used the official CrossCodeEval data for evaluation, which uses chunk size 10 for retrieval. For RepoEval and CrossCodeLongEval, the chunk size is as specified in the paper.

Got it! Thanks for your reply
